config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	scope "(:locale)", locale:/ru|en/ do
		root 'campaigns#index'
		resources :campaigns do 
			resources :comments
		end

		resources :tags, only: [:index, :show]
		resources :categories, only: [:show]

		namespace :admin do
			resources :categories, except: [:show]
			resources :users
		end

	end
end

app/models/campaign.rb
class Campaign < ApplicationRecord

	has_one_attached :image
	has_many :taggings,  dependent: :destroy
	has_many :tags, through: :taggings
	has_many :comments, dependent: :destroy
	validates :title, :summary, :body, :target_amount, presence: true
	validates :target_amount, numericality: {only_integer: true, greater_than: 10}
	belongs_to :category
	belongs_to :user

	def all_tags
		self.tags.map(&:name).join(', ')
	end

	def all_tags=(names)
		self.tags = names.split(',').map do |name|
			Tag.where(name: name.strip).first_or_create
		end
	end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_campaign, only: [:show,:edit,:update,:destroy]
    before_action :owner, only: [:edit, :update, :destroy]

	def index
		@campaigns = Campaign.paginate(page: params[:page], per_page: 5)
	end

	def show
		@comment = Comment.new
	end

	def new
		@campaign = Campaign.new
	end

	def create
		@campaign = current_user.campaigns.build(campaign_params)
		if @campaign.save
			redirect_to @campaign, success: 'Кампания создана'
		else
			flash.now[:danger] = 'Кампания не создана'
			render :new
		end
	end

	def edit
	end

	def update
		if @campaign.update_attributes(campaign_params)
			redirect_to @campaign, success: 'Кампания обновлена'
		else
			flash.now[:danger] = 'Кампания не обновлена'
			render :edit
		end
	end

	def destroy
		@campaign.destroy
		redirect_to campaigns_path
	end


	def owner
		unless @article.user == current_user || current_user.admin?
			redirect_to root_path, danger: 'Нет доступа'
		end
	end

	private
	def set_campaign
		@campaign = Campaign.find(params[:id])
	end

	def campaign_params
		params.require(:campaign).permit(:title, :summary, :body, :target_amount, :image, :all_tags, :category_id, :user_id)
	end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper

	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end
end

app/views/campaigns/_campaign.html.erb
<article class="campaign">
	<section class="campaign-head">
		<h2><%= link_to campaign.title, campaign_path(campaign) %></h2>
		<small>
			<time><%= campaign.created_at.to_date.strftime("%d %B, %Y")%>	</time>
			|

			<% if campaign.category.present? %>
			<%= link_to campaign.category.name,campaign.category%>
			<% end %>


			<% if user_signed_in? && (current_user.admin? || campaign.user == current_user) %>
			|

			<%= link_to t('common.edit'),edit_campaign_path(campaign), class: 'btn btn-outline-primary btn-sm'%>
			|

			<%= link_to t('common.delete'),campaign_path(campaign), method: :delete, data: {confirm:  t('common.quest_to_delete')},class: 'btn btn-outline-danger btn-sm'%>
			<% end %>
		</small>
	</section>

	<section class="campaign-summary">
		<%= campaign.summary %>
	</section>

	<section class="post-summary clearfix">
		<%= image_tag(campaign.image) if campaign.image.attached? %>
	</section>

	<section class="footer-summary">
		<%= raw campaign.tags.sort_by(&:name).map(&:name).map {|t| link_to t, tag_path(t), class: 'badge badge-primary'}.join(' ') %>
	</section>
</article>

app/views/campaigns/_form.html.erb
<% if @campaign.errors.any? %>
<div class="alert alert-danger"> 
	<h5><%= t('common.errors') %></h5>
	<ul>
		<% @campaign.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<%end%>
	</ul>
</div>
<%end%>

<%= form_for @campaign, html: {multipart: true}, local: true do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title,class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :summary %>
		<%= f.text_area :summary,class: 'form-control' %>
	</div>


	<div class="form-group">
		  <%= f.label :body %>
		  <%= f.text_area :body ,class: 'form-control' %>
	</div>


	<div class="form-group">
		  <%= f.label :target_amount %>
		  <%= f.number_field :target_amount ,class: 'form-control' %>
	</div>


	<div class="field">
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>

	<div class="form-group">
		<%= f.label :category_id %>
		<%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true}, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :all_tags %>
		<%= f.text_field :all_tags, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.submit t('.submit', action: @campaign.new_record? ? t('common.create') : t('common.edit')),class:'btn btn-primary' %>
	</div>
<% end %>

app/views/campaigns/edit.html.erb
<h1><%=I18n.t('campaigns.edit.title')%></h1>

<%= render 'form' %>

app/views/campaigns/index.html.erb
<h1><%=I18n.t('campaigns.index.title')%></h1>

<%= render @campaigns %>

<%= will_paginate @campaigns, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/campaigns/new.html.erb
<h1><%=I18n.t('campaigns.new.title')%></h1>

<%= render 'form' %>

app/views/campaigns/show.html.erb
<article class="campaign">
	<section class="campaign-head">
		<h1><%= @campaign.title %></h1>
		<small>
			<time><%= @campaign.created_at.to_date.strftime("%d %B, %Y")%>	</time>

			<% if @campaign.category.present? %>
			<%= link_to @campaign.category.name,@campaign.category%>
			<% end %>

		</small>
	</section>

	<div class="container main", style="width:700px; height: auto">
		<%= image_tag(@campaign.image,style:'width:100%') if @campaign.image.attached?%>
	</div>

	<section class="campaign-body">
		<%= markdown(@campaign.body) %>
	</section>
</article>


<div class="comments">
	<% unless @campaign.comments.empty? %>
	<h2>Comments</h2>
	<div class="comments p-2">
		<%= render @campaign.comments %>
	</div>
	<% end %>
</div>
<% if user_signed_in? %>

<%= render 'comments/form' %>

<% end %>