config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	scope "(:locale)", locale:/ru|en/ do
		root 'campaigns#index'
		resources :campaigns do 
			resources :comments
		end

		resources :tags, only: [:index, :show]
		resources :categories, only: [:show]

		namespace :admin do
			resources :categories, except: [:show]
			resources :users
		end

	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :campaigns
	validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	 before_action :set_category, only: [:edit,:update,:destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория создана'
    else
      flash.now[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория обновлена'
    else
      flash.now[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	 before_action :set_category, only: :show

  def show
    @campaigns = Campaign.where(category_id: @category).paginate(page: params[:page], per_page: 5)
  end


  private
  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
<div class="alert alert-danger"> 
	<h5><%= t('common.errors') %></h5>
	<ul>
		<% @category.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<%end%>
	</ul>
</div>
<%end%>

<%= form_for @category do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name,class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.submit t('.submit', action: @category.new_record? ? t('common.create') : t('common.edit')),class:'btn btn-primary' %>
	</div>
<% end %>

app/views/categories/index.html.erb
<h1>
  <%= t('.title') %>
</h1>

<div class="buttons_panel">
  <%= link_to t('categories.new.title'), new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th><%= t('.title')%></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= category.name %></td>
        <td>
          <%= link_to t('common.edit'), edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to t('common.delete'), category_path(category), method: :delete, data: {confirm: t('common.quest_to_delete')}, class: 'btn btn-outline-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/categories/show.html.erb
<h1><%=@category.name%></h1>

<%= render @campaigns %>

<%= will_paginate @campaigns, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>