config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	scope "(:locale)", locale:/ru|en/ do
		root 'campaigns#index'
		resources :campaigns do 
			resources :comments
		end

		resources :tags, only: [:index, :show]
		resources :categories, only: [:show]

		namespace :admin do
			resources :categories, except: [:show]
			resources :users
		end

	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord

	has_one_attached :image
	has_many :taggings,  dependent: :destroy
	has_many :tags, through: :taggings
	has_many :comments, dependent: :destroy
	validates :title, :summary, :body, :target_amount, presence: true
	validates :target_amount, numericality: {only_integer: true, greater_than: 10}
	belongs_to :category
	belongs_to :user

	def all_tags
		self.tags.map(&:name).join(', ')
	end

	def all_tags=(names)
		self.tags = names.split(',').map do |name|
			Tag.where(name: name.strip).first_or_create
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :campaigns
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :campaign
  belongs_to :user
  validates :reply, presence: true 
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :campaigns, through: :taggings

	def self.counts
		self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :campaign
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :campaigns
  has_many :comments, dependent: :destroy
  validates :username, presence: true
  devise :database_authenticatable, :registerable,:omniauthable,
         :recoverable, :rememberable, :validatable
         
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected

  def check_admin
    redirect_to root_path, alert: 'У вас нет прав доступа к данной странице' unless current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	 before_action :set_category, only: [:edit,:update,:destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория создана'
    else
      flash.now[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория обновлена'
    else
      flash.now[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	add_flash_types :success,:danger,:info,:warning
	before_action :set_locale

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username])
	end

	private

	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
	end



	def default_url_options(options = {})
		{locale: I18n.locale}.merge options
	end


	def after_sign_in_path_for(resource)
		request.env['omniauth.origin'] || root_path
	end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_campaign, only: [:show,:edit,:update,:destroy]
    before_action :owner, only: [:edit, :update, :destroy]

	def index
		@campaigns = Campaign.paginate(page: params[:page], per_page: 5)
	end

	def show
		@comment = Comment.new
	end

	def new
		@campaign = Campaign.new
	end

	def create
		@campaign = current_user.campaigns.build(campaign_params)
		if @campaign.save
			redirect_to @campaign, success: 'Кампания создана'
		else
			flash.now[:danger] = 'Кампания не создана'
			render :new
		end
	end

	def edit
	end

	def update
		if @campaign.update_attributes(campaign_params)
			redirect_to @campaign, success: 'Кампания обновлена'
		else
			flash.now[:danger] = 'Кампания не обновлена'
			render :edit
		end
	end

	def destroy
		@campaign.destroy
		redirect_to campaigns_path
	end


	def owner
		unless @article.user == current_user || current_user.admin?
			redirect_to root_path, danger: 'Нет доступа'
		end
	end

	private
	def set_campaign
		@campaign = Campaign.find(params[:id])
	end

	def campaign_params
		params.require(:campaign).permit(:title, :summary, :body, :target_amount, :image, :all_tags, :category_id, :user_id)
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	 before_action :set_category, only: :show

  def show
    @campaigns = Campaign.where(category_id: @category).paginate(page: params[:page], per_page: 5)
  end


  private
  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_comment, only: [:edit, :update, :show, :destroy]
	before_action :set_campaign


	def new
		@comment=Comment.new
	end

	def create
		@comment = @campaign.comments.create(params[:comment].permit(:reply,:campaign_id))
		@comment.user = current_user

		respond_to do |format|
			if @comment.save
				format.html {redirect_to campaign_path(@campaign)}
				#format.js
			else
				format.html {redirect_to campaign_path(@campaign), notice:"Comment was saved"}
				#format.js
			end
		end
	end

	def destroy
		@comment = @campaign.comments.find(params[:id])
		if @comment.user == current_user
			@comment.destroy
			redirect_to campaign_path(@campaign)
		else
			redirect_to campaign_path(@cmpaign), danger: 'Нет доступа'
		end
	end

	private

	def set_campaign
		@campaign = Campaign.find(params[:campaign_id])
	end


	def set_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:reply)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: params[:id])
		@campaigns = @tag.campaigns	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

  def bootstrap_class_for(name)
    {
        success: 'alert-success',
        error: 'alert-danger',
        danger: 'alert-danger',
        alert: 'alert-warning',
        notice: 'alert-info',
    }[name.to_sym] || name
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/_admin_panel.html.erb
<div class="dropdown show mx-2">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= t('admin.admin_panel.admin_panel') %>
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to t('admin.admin_panel.categories_manage'), admin_categories_path, class: 'dropdown-item' %>
    <%= link_to t('.change_users'), admin_users_path, class: 'dropdown-item' %>
  </div>
</div>

app/views/layouts/_categories.html.erb
  <div class="card-block categories p-4 text-center">
    <div class="btn-group">
      <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= t('layouts.select_category') %>
      </button>
      <div class="dropdown-menu">
        <% Category.all.each do |category| %>
          <li class="nav-item">
            <%= link_to category.name, category, class: "nav-link" %>
          </li>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to t('navigation.all_campaigns'), campaigns_path, class: 'nav-link' %>
    </li>
  </ul>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="col-md-4">
        <%= render 'layouts/categories' %>
      </div>
    </li>
  </ul>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="col-md-4">
        <% if user_signed_in? && current_user.admin? %>
        <%= render 'layouts/admin_panel' %>
        <% end %>
      </div>
    </li>
  </ul>


  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
  </form>


  <ul class="navbar-nav pull-xs-right">

    <li class="nav-item<%= " active" if I18n.locale == :ru %>">
      <%= link_to "Рус", {locale: :ru}, class: "nav-link" %>
    </li>
    <li class="nav-item<%= " active" if I18n.locale == :en %>">
      <%= link_to "Eng", {locale: :en}, class: "nav-link" %>
    </li>



    <% if user_signed_in? %>
    <%= render 'layouts/user_panel' %>
    <% else %>
    <li class="navbar-nav mr-auto">
      <%= link_to t('.log_in_sign_up'), new_user_session_path, class: "btn btn-dark" %>
    </li>
    <% end %>
  </ul>
</div>
</nav>

app/views/layouts/_tags_cloud.html.erb
<div class="card">
  <div class="card-header">
    <h3><%= t('.title') %></h3>
  </div>
  <div class="card-block p-2 text-center tag_cloud">
    <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class%>
    <% end %>
  </div>
</div>

app/views/layouts/_user_panel.html.erb
<div class="btn-group mx-2">
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.username %>
  </button>
  <div class="dropdown-menu">
    <li class="nav-item">
       <%= link_to t('.new_campaign'), new_campaign_path, class: 'nav-link' %>
    </li>

    <li class="nav-item">
      <%= link_to t('.edit_profile'), edit_user_registration_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunding</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <%= render 'layouts/navigation' %>

  <div class="container">
    <div class="container-fluid main">
      <% flash.each do |name, message| %>
      <div class="row">
        <div class="col-md-12">
          <div class="alert <%= bootstrap_class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
        </div>
      </div>
      <% end %>


      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>

        <div class="col-md-3">
          <%= render 'layouts/tags_cloud' %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>